// <auto-generated />
namespace AdChimeProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class migra20230108 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migra20230108));
        
        string IMigrationMetadata.Id
        {
            get { return "202301082335505_migra20230108"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
